# Generated by Django 4.2.26 on 2025-11-27 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='Type of event that triggered this notification', max_length=50)),
                ('event_data', models.JSONField(help_text='Original event data from the source service')),
                ('user_id', models.CharField(blank=True, help_text='ID of the user to notify', max_length=100)),
                ('user_email', models.EmailField(blank=True, help_text='Email of the user to notify', max_length=254)),
                ('user_name', models.CharField(blank=True, help_text='Name of the user to notify', max_length=200)),
                ('subject', models.CharField(help_text='Notification subject/title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the notification was actually sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_service', models.CharField(help_text='Which service generated the original event', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type'], name='notificatio_event_t_c22bab_idx'), models.Index(fields=['user_id'], name='notificatio_user_id_c291d5_idx'), models.Index(fields=['status'], name='notificatio_status_d92267_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
